version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cimade-backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
      # Otras variables de entorno necesarias para tu aplicaci√≥n
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: postgrest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: binex
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - ./data:/var/lib/postgresql/data
